import JSZip from 'jszip';
import { CanvasInformation, IIIFManifestResource } from '@/model';
import { Store } from '@/store';
import { fetchManifest } from '@/utils/iiif';
import { crosswalkAnnotations } from './crosswalkAnnotations';

const createAnnotationPage = (canvas: CanvasInformation, baseUrl: string, store: Store) =>
  store.getAnnotations(`iiif:${canvas.manifestId}:${canvas.id}`).then(annotations => annotations.length > 0 ? {
    '@context': 'http://iiif.io/api/presentation/3/context.json',
    id: `${baseUrl}/${canvas.manifestId}/annotations-${canvas.id}.json`,
    type: 'AnnotationPage',
    items: crosswalkAnnotations(annotations, store)
  } : undefined);

export const exportDerivativeResource = async (resource: IIIFManifestResource, baseUrl: string, store: Store) => {
  const zip = new JSZip();

  // Original manifest
  const manifest = await fetchManifest(resource.uri);

  for (const canvas of resource.canvases) {
    const annotations = await createAnnotationPage(canvas, baseUrl, store);
    if (annotations)
      zip.file(`${resource.id}/annotations-${canvas.id}.json`, JSON.stringify(annotations, null, 2));
  }

  // TODO modify - inject annotation page links and mark the manifest as a derivative (generated by IMMARKUS)
  zip.file(`${resource.id}/manifest.json`, JSON.stringify(manifest, null, 2));

  const blob = await zip.generateAsync({ type:'blob' });

  const anchor = document.createElement('a');
  anchor.href = URL.createObjectURL(blob);
  anchor.download = `${resource.id}.zip`;
  anchor.click();
}