import JSZip from 'jszip';
import { CanvasInformation, IIIFManifestResource } from '@/model';
import { Store } from '@/store';
import { fetchManifest } from '@/utils/iiif';
import { crosswalkAnnotations } from './crosswalkAnnotations';

const createAnnotationPage = (canvas: CanvasInformation, baseUrl: string, store: Store) =>
  store.getAnnotations(`iiif:${canvas.manifestId}:${canvas.id}`).then(annotations => annotations.length > 0 ? {
    '@context': 'http://iiif.io/api/presentation/3/context.json',
    id: `${baseUrl}/${canvas.manifestId}/annotations-${canvas.id}.json`,
    type: 'AnnotationPage',
    items: crosswalkAnnotations(annotations, store)
  } : undefined);

export const exportDerivativeResource = async (resource: IIIFManifestResource, baseUrl: string, store: Store) => {
  const zip = new JSZip();

  // Original manifest
  const manifest = await fetchManifest(resource.uri);

  const annotationPageUrls = new Map<string, string>();

  for (const canvas of resource.canvases) {
    const annotations = await createAnnotationPage(canvas, baseUrl, store);
    if (annotations) {
      zip.file(`${resource.id}/annotations-${canvas.id}.json`, JSON.stringify(annotations, null, 2));
      annotationPageUrls.set(canvas.uri, annotations.id);
    }
  }

  const derivative = {...manifest.source };

  derivative.items = (derivative.items || []).map((canvas: any) => {
    const annotationPageUrl = annotationPageUrls.get(canvas.id);
    if (!annotationPageUrl) return canvas;

    return {
      ...canvas,
      annotations: [{
        id: annotationPageUrl,
        type: 'AnnotationPage'
      }]
    };
  });

  // Note that this erases the original requiredStatement - what's a better approach?
  derivative.requiredStatement = {
    label: { en: ['Attribution'] },
    value: {
      en: [
        `This manifest is a derivative generated by IMMARKUS from the <a href="${resource.uri}">original manifest</a>.`
      ]
    }
  };

  zip.file(`${resource.id}/manifest.json`, JSON.stringify(manifest, null, 2));

  const blob = await zip.generateAsync({ type:'blob' });

  const anchor = document.createElement('a');
  anchor.href = URL.createObjectURL(blob);
  anchor.download = `${resource.id}.zip`;
  anchor.click();
}